VERSION: 2
MODEL:
  META_ARCHITECTURE: "GeneralizedVLRCNN"
  WEIGHTS: <set by load script>
  RPN_ONLY: True
  PIXEL_MEAN: [ 103.530, 116.280, 123.675 ]
  PIXEL_STD: [ 57.375, 57.120, 58.395 ]

  BACKBONE:
    NAME: "build_retinanet_swint_fpn_backbone"
    OUT_CHANNELS: 256
    FREEZE_CONV_BODY_AT: 2

  FPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    OUT_CHANNELS: 256

  SWINT:
    EMBED_DIM: 192
    DEPTHS: (2, 2, 18, 2)
    NUM_HEADS: (6, 12, 24, 48)
    WINDOW_SIZE: 12
    OUT_FEATURES: ["p1", "p2", "p3"]
    OUT_CHANNELS: (192, 384, 768, 1536)
    DROP_PATH_RATE: 0.4

  LANGUAGE_BACKBONE:
    FREEZE: False
    MODEL_TYPE: "bert-base-uncased"
    MASK_SPECIAL: False

  PROPOSAL_GENERATOR:
    NAME: "VLDyHeadModule"

  ANCHOR_GENERATOR:
    SIZES: [[64], [128], [256], [512], [1024]]
    ASPECT_RATIOS: [[1.0]]
    SCALES_PER_OCTAVE: 1

  RPN:
    USE_FPN: True
    IN_FEATURES: ["p4"]

  ROI_HEADS:
    IN_FEATURES: ["p4"]

  DYHEAD:
    CHANNELS: 256
    NUM_CONVS: 8
    USE_GN: True
    USE_DYRELU: True
    USE_DFCONV: True
    USE_DYFUSE: True
    TOPK: 9 # topk for selecting candidate positive samples from each level
    SCORE_AGG: "MEAN"
    LOG_SCALE: 0.0

    USE_CHECKPOINT: True
    FUSE_CONFIG:
      USE_FUSED_FEATURES_DOT_PRODUCT: True
      EARLY_FUSE_ON: True
      TYPE: "MHA-B"
      USE_CLASSIFICATION_LOSS: False
      USE_TOKEN_LOSS: False
      USE_CONTRASTIVE_ALIGN_LOSS: False
      CONTRASTIVE_HIDDEN_DIM: 64
      USE_DOT_PRODUCT_TOKEN_LOSS: True
      USE_LAYER_SCALE: True
      CLAMP_MIN_FOR_UNDERFLOW: True
      CLAMP_MAX_FOR_OVERFLOW: True
      CLAMP_BERTATTN_MIN_FOR_UNDERFLOW: True
      CLAMP_BERTATTN_MAX_FOR_OVERFLOW: True
      CLAMP_DOT_PRODUCT: True
      ADD_LINEAR_LAYER: False

  ATSS:
    SOFT_NMS: False

DATASETS:
  USE_OVERRIDE_CLASS_NAMES: True
  USE_PROMPT_TEMPLATE: True

  SHUFFLE_CAPTION: False  # shuffle the order of class names in the caption
  RANDOM_SAMPLE_NEG: 85
  CONTROL_PROB: (0.0, 0.0, 0.5, 0.0)
  FURTHER_SCREEN: True
  CAPTION_CONF: 0.5
  CAPTION_NMS: -1.0
  CAPTION_MIN_BOX: 1

  TOKEN_SEPARATION: ". "

  PACK_RANDOM_CAPTION_NUMBER: 20
  NO_RANDOM_PACK_PROBABILITY: 0.4
  RANDOM_PACK_PROB: 0.5
  CAPTION_FORMAT_VERSION: "v2"

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800,)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333

AUGMENT:
  MULT_MIN_SIZE_TRAIN: (480,560,640,720,800)

DATALOADER:
  SIZE_DIVISIBILITY: 32
  ASPECT_RATIO_GROUPING: False

SOLVER:
  OPTIMIZER: ADAMW
  BASE_LR: 0.0001
  LANG_LR: 0.00001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_SCHEDULE: True
  STEPS: (0.67, 0.89)
  MAX_ITER: 10000
  IMS_PER_BATCH: 1
  WARMUP_ITERS: 100
  WARMUP_FACTOR: 0.001

  STEP_PATIENCE: 3
  CHECKPOINT_PER_EPOCH: 1.0
  AUTO_TERMINATE_PATIENCE: 8
  MODEL_EMA: 0.0
  TUNING_HIGHLEVEL_OVERRIDE: full

  FIND_UNUSED_PARAMETERS: False
  TEST_WITH_INFERENCE: True
  USE_AUTOSTEP: True

  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 1.0
    NORM_TYPE: 2.0

TEST:
  DURING_TRAINING: True
  IMS_PER_BATCH: 1
  EVAL_TASK: detection
